-- ============================================================
-- DEMO data for testing the official scoresheet locally.
-- Everything is tagged "DEMO" and removed by scoresheet-cleanup.sql.
-- Generated by gen_scoresheet_seed.py; match DEMO-1 is fully balanced.
-- ============================================================
do $$
declare
  v_t bigint; v_away bigint; v_home bigint; v_m1 bigint;
begin
  if exists (select 1 from tournaments where tournament_name like 'DEMO %') then
    raise exception 'Demo data already exists - run scoresheet-cleanup.sql first.';
  end if;

  insert into tournaments (tournament_name, start_date, end_date, status)
    values ('DEMO - Ujian Scoresheet', current_date - 3, current_date + 4, 'ongoing') returning tournament_id into v_t;
  insert into clubs (club_name, state, manager_name, color)
    values ('DEMO Harimau KL', 'Kuala Lumpur', 'Pengurus Demo', '#c2410c') returning club_id into v_away;
  insert into clubs (club_name, state, manager_name, color)
    values ('DEMO Helang Perak', 'Perak', 'Pengurus Demo', '#15803d') returning club_id into v_home;
  insert into players (club_id, jersey_number, first_name, last_name, position) values
    (v_away, 7, 'Ali', 'Hassan', 'CF'),
    (v_away, 12, 'Wong', 'Kah Meng', 'SS'),
    (v_away, 21, 'Tan', 'Wei Jie', '1B'),
    (v_away, 4, 'Rajesh', 'Kumar', 'C'),
    (v_away, 15, 'Lim', 'Boon Hock', '3B'),
    (v_away, 9, 'Hafiz', 'Rahman', 'LF'),
    (v_away, 3, 'Daniel', 'Lee', '2B'),
    (v_away, 27, 'Arif', 'Zakaria', 'RF'),
    (v_away, 33, 'Kumar', 'Selvam', 'DH'),
    (v_away, 18, 'Syafiq', 'Ismail', 'OF'),
    (v_away, 11, 'Ahmad', 'Zulkifli', 'P'),
    (v_away, 40, 'Lee', 'Chun Hao', 'P'),
    (v_away, 22, 'Nabil', 'Farhan', 'IF');
  insert into players (club_id, jersey_number, first_name, last_name, position) values
    (v_home, 2, 'Faris', 'Aiman', 'SS'),
    (v_home, 6, 'Nicholas', 'Ong', '2B'),
    (v_home, 8, 'Irfan', 'Hakim', 'CF'),
    (v_home, 25, 'Kenny', 'Chin', '1B'),
    (v_home, 10, 'Muthu', 'Raj', 'C'),
    (v_home, 14, 'Amirul', 'Hakimi', '3B'),
    (v_home, 5, 'Jason', 'Yap', 'LF'),
    (v_home, 19, 'Zulhilmi', 'Aziz', 'RF'),
    (v_home, 30, 'Harith', 'Danial', 'DH'),
    (v_home, 17, 'Faizal', 'Rosli', 'P'),
    (v_home, 44, 'Chong', 'Wei Han', 'P'),
    (v_home, 1, 'Aiman', 'Syahmi', 'OF'),
    (v_home, 23, 'Ravi', 'Chandran', 'IF');

  -- DEMO-1: completed, full balanced scoresheet (starts 3:00 PM MYT two days ago, 2:41 long)
  insert into matches (tournament_id, match_number, home_team_id, away_team_id, match_date, ended_at, venue, status, home_score, away_score, away_lob, home_lob, round_name)
    values (v_t, 'DEMO-1', v_home, v_away,
            (current_date - 2)::timestamp + interval '15 hours' - interval '8 hours',
            (current_date - 2)::timestamp + interval '17 hours 41 minutes' - interval '8 hours',
            'Stadium Bola Lisut Demo, Ipoh', 'completed', 4, 7, 8, 6, 'Separuh Akhir') returning match_id into v_m1;
  -- DEMO-2: completed, no scoresheet yet (try the admin editor here)
  insert into matches (tournament_id, match_number, home_team_id, away_team_id, match_date, venue, status, home_score, away_score, round_name)
    values (v_t, 'DEMO-2', v_away, v_home, (current_date - 1)::timestamp + interval '7 hours', 'Padang Demo, Kuala Lumpur', 'completed', 5, 3, 'Kumpulan');
  -- DEMO-3: scheduled
  insert into matches (tournament_id, match_number, home_team_id, away_team_id, match_date, venue, status, round_name)
    values (v_t, 'DEMO-3', v_home, v_away, (current_date + 2)::timestamp + interval '7 hours', 'Stadium Bola Lisut Demo, Ipoh', 'scheduled', 'Akhir');

  insert into match_innings (match_id, inning, away_runs, home_runs) values
    (v_m1, 1, 0, 1), (v_m1, 2, 2, 0), (v_m1, 3, 0, 0), (v_m1, 4, 0, 2), (v_m1, 5, 3, 0), (v_m1, 6, 0, 0), (v_m1, 7, 2, 1), (v_m1, 8, 0, 0), (v_m1, 9, 0, 0);

  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 1, 'CF', 5, 2, 3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 7;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 2, 'SS', 4, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 4, 1, 0, 0, 0
    from players where club_id = v_away and jersey_number = 12;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 3, '1B', 4, 1, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 9, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 21;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 4, 'C', 4, 1, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 7, 1, 0, 1, 1, 0
    from players where club_id = v_away and jersey_number = 4;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 5, '3B', 4, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 15;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 6, 'LF', 4, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 9;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 7, '2B', 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 3, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 3;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 8, 'RF', 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 27;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 9, 'DH', 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 33;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, false, 9, 'PH', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 18;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, null, 'P', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 11;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, false, null, 'P', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    from players where club_id = v_away and jersey_number = 40;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 1, 'SS', 4, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 5, 1, 0, 0, 0
    from players where club_id = v_home and jersey_number = 2;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 2, '2B', 4, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 3, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 6;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 3, 'CF', 4, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 8;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 4, '1B', 3, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 8, 1, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 25;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 5, 'C', 4, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 6, 1, 0, 0, 3, 1
    from players where club_id = v_home and jersey_number = 10;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 6, '3B', 3, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0
    from players where club_id = v_home and jersey_number = 14;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 7, 'LF', 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 5;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 8, 'RF', 3, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 19;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, 9, 'DH', 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 30;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, true, null, 'P', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 17;
  insert into player_match_stats (player_id, match_id, started, batting_order, position_played, at_bats, runs, hits, rbi, doubles, triples, home_runs, sac_hits, sac_flies, walks, hit_by_pitch, reached_on_error, strikeouts_swinging, strikeouts_looking, stolen_bases, caught_stealing, putouts, assists, errors, runners_caught_stealing, stolen_bases_allowed, passed_balls)
    select player_id, v_m1, false, null, 'P', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    from players where club_id = v_home and jersey_number = 44;
  insert into match_pitching_stats (player_id, match_id, pitch_order, started, decision, outs, at_bats, hits, earned_runs, unearned_runs, walks, strikeouts_swinging, strikeouts_looking, wild_pitches, balks)
    select player_id, v_m1, 1, true, 'win'::pitching_decision, 21, 25, 6, 3, 0, 3, 5, 2, 0, 0
    from players where club_id = v_away and jersey_number = 11;
  insert into match_pitching_stats (player_id, match_id, pitch_order, started, decision, outs, at_bats, hits, earned_runs, unearned_runs, walks, strikeouts_swinging, strikeouts_looking, wild_pitches, balks)
    select player_id, v_m1, 2, false, 'save'::pitching_decision, 6, 8, 2, 1, 0, 0, 2, 0, 0, 0
    from players where club_id = v_away and jersey_number = 40;
  insert into match_pitching_stats (player_id, match_id, pitch_order, started, decision, outs, at_bats, hits, earned_runs, unearned_runs, walks, strikeouts_swinging, strikeouts_looking, wild_pitches, balks)
    select player_id, v_m1, 1, true, 'loss'::pitching_decision, 16, 24, 8, 4, 1, 3, 3, 1, 1, 0
    from players where club_id = v_home and jersey_number = 17;
  insert into match_pitching_stats (player_id, match_id, pitch_order, started, decision, outs, at_bats, hits, earned_runs, unearned_runs, walks, strikeouts_swinging, strikeouts_looking, wild_pitches, balks)
    select player_id, v_m1, 2, false, null, 11, 14, 3, 1, 1, 1, 2, 0, 0, 0
    from players where club_id = v_home and jersey_number = 44;
end $$;
